
services:
  jkbooks-next:
    container_name:  jkbooks-next
    restart: always
    image: node:20.10.0
    ports:
      - 5000:3001
    environment:
      - PORT=3001
    volumes:
      - ./:/usr/src/jkbooks-next
    working_dir: /usr/src/jkbooks-next
    networks:
      - client-network
    # FOR PRODUCTION
    command: bash -c "yarn install && yarn run build && yarn run start"
    # FOR DEVELOPMENT
    # command: bash -c "npm install && npm run build && npm run start:dev"


networks:
  client-network:
    driver: bridge