export enum FaqCategory {
	BOOK = 'BOOK',
	PAYMENTS = 'PAYMENTS',
	BUYERS = 'BUYERS',
	PUBLISHERS = 'PUBLISHERS',
	MEMBERSHIP = 'MEMBERSHIP',
	COMMUNITY = 'COMMUNITY',
	OTHER = 'OTHER',
}

export enum FaqStatus {
	HOLD = 'HOLD',
	ACTIVE = 'ACTIVE',
	DELETE = 'DELETE',
}
